server:
  port: 3000
  servlet:
    context-path: /api

spring:
  application:
    name: backend

  devtools:
    livereload:
      enabled: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  redis:
    host: 192.168.92.4 # Docker-compose IP | change to localhost to run locally
    port: 6379
#   password: <no password>
#   timeout: 10000
