timeZone: America/Buenos_Aires

server:
  port: 3000
  servlet:
    context-path: /api

spring:
  application:
    name: backend

  devtools:
    livereload:
      enabled: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  data:
    mongodb:
      uri: "mongodb://root:example@127.0.0.1:27017/tacs?retryWrites=true&w=majority&authSource=admin"


