timeZone: America/Buenos_Aires

server:
  port: 3000
  servlet:
    context-path: /api

spring:
  application:
    name: backend

  devtools:
    livereload:
      enabled: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  data:
    mongodb:
      uri: mongodb://tacs:4uKZYCW3sZDRpxv@docdb-mongo.cluster-cqoii29d68ex.us-east-1.docdb.amazonaws.com:27017/?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
